/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/matrices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compute Matrices
         * @description Compute the geometric matrix bundle for a coil (runs the FEM solve).
         *
         *     The slow call (~seconds). Cache the returned bundle on the client and
         *     pass it back to the fast endpoints to avoid recomputing while adjusting
         *     non-geometry parameters.
         */
        post: operations["compute_matrices_simulation_matrices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze
         * @description Full JavaTC-style analysis plus the coupled solve (splitting).
         */
        post: operations["analyze_simulation_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/impedance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Impedance
         * @description Primary driving-point impedance sweep with the secondary installed.
         *
         *     The complex impedance looking into the primary tank terminals at each
         *     requested frequency - the coupled-system feature that shows the split
         *     resonances as peaks. Requires a primary tank capacitance.
         */
        post: operations["impedance_simulation_impedance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/spice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spice
         * @description Export the coupled system as a SPICE subcircuit.
         *
         *     A network reproducing the coupled model's AC/transient behavior, for
         *     dropping the coil into a larger SPICE schematic. Requires a primary
         *     tank capacitance.
         */
        post: operations["spice_simulation_spice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/field": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Field
         * @description Operating electric or magnetic field on a regular (r, z) grid.
         *
         *     Superposes precomputed basis fields (cached by geometry) with the phasor
         *     drive at the requested frequency and primary current, so re-rendering a
         *     new drive is fast. Requires a primary with a tank capacitance.
         */
        post: operations["field_simulation_field_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Root
         * @description Root endpoint providing basic API information.
         */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisResponse
         * @description Full JavaTC-style analysis. primary/coupling are null for a coil
         *     with no primary; coupled is null without a primary tank capacitance.
         */
        AnalysisResponse: {
            secondary: components["schemas"]["SecondaryOutputs"];
            /** @description Voltage and current eigenmode shapes of the secondary */
            modes: components["schemas"]["EigenModesOutputs"];
            primary?: components["schemas"]["PrimaryOutputs"] | null;
            coupling?: components["schemas"]["CouplingOutputs"] | null;
            coupled?: components["schemas"]["CoupledOutputs"] | null;
            /** @description The matrix bundle used (echo it back to reuse) */
            bundle: components["schemas"]["MatrixBundleSchema"];
        };
        /**
         * AnalyzeRequest
         * @description Request a full analysis, reusing a precomputed matrix bundle.
         *
         *     The bundle must match the coil's geometry (its geometry_fingerprint is
         *     validated); a mismatch returns 409. Omit the bundle to have the server
         *     compute it inline (equivalent to calling the matrices endpoint first,
         *     but without returning the bundle to the client).
         */
        AnalyzeRequest: {
            coil: components["schemas"]["SimulatableTeslaCoilSchema"];
            bundle?: components["schemas"]["MatrixBundleSchema"] | null;
        };
        /**
         * BoundaryConditionSchema
         * @description Boundary condition on a simulation-domain wall.
         */
        BoundaryConditionSchema: {
            /**
             * @description Dirichlet (fixed potential) or Neumann (zero normal field)
             * @default dirichlet
             */
            bc_type: components["schemas"]["BoundaryConditionTypeSchema"];
            /**
             * Value
             * @description Potential value (Dirichlet only)
             * @default 0
             */
            value: number;
        };
        /**
         * BoundaryConditionTypeSchema
         * @enum {string}
         */
        BoundaryConditionTypeSchema: "dirichlet" | "neumann";
        /**
         * CircleSchema
         * @description A circular (r, z) cross section - a toroid when revolved off-axis.
         */
        CircleSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "circle";
            /**
             * Center
             * @description Center point (r, z)
             */
            center: [
                number,
                number
            ];
            /**
             * Radius
             * @description Radius
             */
            radius: number;
        };
        /**
         * CircularCrossSectionSchema
         * @description Round conductor of a given diameter.
         */
        CircularCrossSectionSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "circular";
            /** Diameter */
            diameter: number;
        };
        /**
         * CoupledOutputs
         * @description Full coupled primary-secondary solve. Present only when the primary
         *     has a tank capacitance.
         */
        CoupledOutputs: {
            /**
             * Mode Frequencies
             * @description Coupled resonant frequencies (Hz), ascending
             */
            mode_frequencies: number[];
            /**
             * Split Lower
             * @description Lower split-pair frequency (Hz)
             */
            split_lower: number;
            /**
             * Split Upper
             * @description Upper split-pair frequency (Hz)
             */
            split_upper: number;
            /**
             * Frequency Split
             * @description Upper - lower (Hz)
             */
            frequency_split: number;
        };
        /** CouplingOutputs */
        CouplingOutputs: {
            /** Mutual Inductance */
            mutual_inductance: number;
            /** Coupling Coefficient */
            coupling_coefficient: number;
            /** Half Cycles For Energy Transfer */
            half_cycles_for_energy_transfer: number;
            /**
             * Energy Transfer Time
             * @description Null when the primary tank frequency is undefined
             */
            energy_transfer_time?: number | null;
        };
        /**
         * EigenModesOutputs
         * @description The secondary's transmission-line eigenmodes: for every eigenfrequency,
         *     the voltage mode shape (nodal voltages along the winding) and the current
         *     mode shape (segment currents).
         *
         *     Amplitudes are the raw eigenvector values (arbitrary overall scale), with
         *     only the physically-arbitrary eigenvector SIGN fixed to a convention
         *     (top-node voltage positive) so a mode does not flip between analyses.
         *     Positions are arc length in meters along the winding centerline, measured
         *     from the grounded base (0) to the top terminal (``winding_length``).
         *
         *     The voltage profile includes the grounded base node (value 0 at arc length
         *     0), so ``voltage_positions`` has one more entry than ``current_positions``.
         */
        EigenModesOutputs: {
            /**
             * Frequencies
             * @description Eigenfrequencies (Hz), ascending; one per mode
             */
            frequencies: number[];
            /**
             * Voltage Positions
             * @description Arc length (m) along the winding for each voltage node
             */
            voltage_positions: number[];
            /**
             * Current Positions
             * @description Arc length (m) along the winding for each current segment
             */
            current_positions: number[];
            /**
             * Voltage Modes
             * @description Per-mode nodal voltage shape (len == len(voltage_positions))
             */
            voltage_modes: number[][];
            /**
             * Current Modes
             * @description Per-mode segment current shape (len == len(current_positions))
             */
            current_modes: number[][];
        };
        /**
         * FieldRequest
         * @description Operating electric or magnetic field on a regular (r, z) grid.
         *
         *     Reuses a matrix bundle for the drive solve; the basis fields are cached
         *     server-side by geometry, so changing the drive re-renders fast. Requires
         *     a primary with a tank capacitance.
         */
        FieldRequest: {
            coil: components["schemas"]["SimulatableTeslaCoilSchema"];
            bundle?: components["schemas"]["MatrixBundleSchema"] | null;
            /**
             * Field Type
             * @description Which field to compute
             * @default electric
             * @enum {string}
             */
            field_type: "electric" | "magnetic";
            /**
             * Frequency Hz
             * @description Sinusoidal drive frequency
             */
            frequency_hz: number;
            /**
             * Primary Current
             * @description Primary current magnitude [A] (drive amplitude)
             * @default 1
             */
            primary_current: number;
            /**
             * Reference Mode
             * @description Primary common-mode reference (E-field only)
             * @default floating
             * @enum {string}
             */
            reference_mode: "floating" | "grounded";
            /**
             * Hot End
             * @description Which primary end carries V_p (E-field only)
             * @default outer
             * @enum {string}
             */
            hot_end: "inner" | "outer";
            /**
             * Grid Nr
             * @description Grid samples across r
             * @default 120
             */
            grid_nr: number;
            /**
             * Grid Nz
             * @description Grid samples across z
             * @default 180
             */
            grid_nz: number;
        };
        /**
         * FieldResponse
         * @description A complex field sampled on a regular grid, row-major (z outer, r
         *     inner). The client reshapes ``real``/``imag`` to (nz, nr) and takes the
         *     gradient/curl (using unit_scale for metres) for E or B.
         */
        FieldResponse: {
            /**
             * Field Type
             * @enum {string}
             */
            field_type: "electric" | "magnetic";
            /**
             * Quantity
             * @description 'potential [V]' (E) or 'vector_potential [T*m]' (B)
             */
            quantity: string;
            /** Nr */
            nr: number;
            /** Nz */
            nz: number;
            /** R Min */
            r_min: number;
            /** R Max */
            r_max: number;
            /** Z Min */
            z_min: number;
            /** Z Max */
            z_max: number;
            /**
             * Unit Scale
             * @description Metres per coil unit
             */
            unit_scale: number;
            /**
             * Real
             * @description Re(field), nr*nz row-major
             */
            real: number[];
            /**
             * Imag
             * @description Im(field), nr*nz row-major
             */
            imag: number[];
            /**
             * Mask
             * @description True where the field is defined
             */
            mask: boolean[];
            bundle: components["schemas"]["MatrixBundleSchema"];
        };
        /** GroundedConductorSchema */
        GroundedConductorSchema: {
            /** @default copper */
            material: components["schemas"]["MaterialSchema"];
            /**
             * Shape
             * @description (r, z) cross-section shape
             */
            shape: components["schemas"]["CircleSchema"] | components["schemas"]["RectangleSchema"] | components["schemas"]["PolygonSchema"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImpedancePoint */
        ImpedancePoint: {
            /** Frequency Hz */
            frequency_hz: number;
            /**
             * Resistance
             * @description Re(Z) [Ohm]
             */
            resistance: number;
            /**
             * Reactance
             * @description Im(Z) [Ohm]
             */
            reactance: number;
            /**
             * Magnitude
             * @description |Z| [Ohm]
             */
            magnitude: number;
        };
        /**
         * ImpedanceRequest
         * @description Primary driving-point impedance sweep with the secondary installed.
         *
         *     Reuses a matrix bundle (fast). Requires a primary tank capacitance.
         */
        ImpedanceRequest: {
            coil: components["schemas"]["SimulatableTeslaCoilSchema"];
            bundle?: components["schemas"]["MatrixBundleSchema"] | null;
            /**
             * Frequencies Hz
             * @description Frequencies to evaluate (Hz)
             */
            frequencies_hz: number[];
            /**
             * Include Losses
             * @description Use AC/DC resistances so peaks are finite
             * @default false
             */
            include_losses: boolean;
            /**
             * Include Tank
             * @description Include the series tank capacitor (full LC input)
             * @default true
             */
            include_tank: boolean;
        };
        /** ImpedanceResponse */
        ImpedanceResponse: {
            /** Points */
            points: components["schemas"]["ImpedancePoint"][];
            bundle: components["schemas"]["MatrixBundleSchema"];
        };
        /**
         * LinearPrimarySchema
         * @description A primary wound along a straight (r, z) centerline.
         */
        LinearPrimarySchema: {
            /** @default copper */
            material: components["schemas"]["MaterialSchema"];
            /**
             * Turn Fxn
             * @description Cumulative turn profile
             */
            turn_fxn: components["schemas"]["UniformTurnProfileSchema"];
            /**
             * Cross Section
             * @description Conductor cross-section
             */
            cross_section: components["schemas"]["CircularCrossSectionSchema"] | components["schemas"]["RectangularCrossSectionSchema"];
            /**
             * Start
             * @description Winding start (r, z)
             */
            start: [
                number,
                number
            ];
            /**
             * End
             * @description Winding end (r, z)
             */
            end: [
                number,
                number
            ];
            /**
             * Tank Capacitance
             * @description Tank capacitance (Farads)
             * @default 0
             */
            tank_capacitance: number;
            /**
             * Lead Length
             * @description Connection lead length
             * @default 0
             */
            lead_length: number;
            /**
             * Lead Dia
             * @description Connection lead diameter
             * @default 0
             */
            lead_dia: number;
        };
        /**
         * LinearSecondaryConductorSchema
         * @description A secondary wound along a straight (r, z) centerline.
         */
        LinearSecondaryConductorSchema: {
            /** @default copper */
            material: components["schemas"]["MaterialSchema"];
            /**
             * Turn Fxn
             * @description Cumulative turn profile
             */
            turn_fxn: components["schemas"]["UniformTurnProfileSchema"];
            /**
             * Start
             * @description Winding start (r, z)
             */
            start: [
                number,
                number
            ];
            /**
             * End
             * @description Winding end (r, z)
             */
            end: [
                number,
                number
            ];
            /**
             * Wire Dia
             * @description Wire diameter
             */
            wire_dia: number;
        };
        /**
         * MaterialSchema
         * @description Conductor material (maps to app.models.materials.Material).
         * @enum {string}
         */
        MaterialSchema: "copper" | "aluminum";
        /**
         * MatricesRequest
         * @description Request the geometric matrix bundle for a coil (the slow FEM path).
         */
        MatricesRequest: {
            coil: components["schemas"]["SimulatableTeslaCoilSchema"];
        };
        /**
         * MatrixBundleSchema
         * @description Geometry-only matrices (geometric units) plus their provenance.
         *
         *     Treat this as an opaque token on the client: obtain it from the
         *     matrices endpoint, cache it, and send it back to the analyze endpoint.
         *     The geometry_fingerprint guards against applying it to a coil whose
         *     geometry has changed.
         */
        MatrixBundleSchema: {
            /**
             * Nodal Capacitance
             * @description (N+1)x(N+1) geometric nodal capacitance matrix
             */
            nodal_capacitance: number[][];
            /**
             * Topload Charge
             * @description Length-(N+1) geometric topload charge per tent solve
             */
            topload_charge: number[];
            /**
             * Inductance
             * @description NxN geometric segment inductance matrix
             */
            inductance: number[][];
            /**
             * Coupling
             * @description Length-N geometric coupling vector (empty if no primary)
             */
            coupling: number[];
            /**
             * Discretization Order
             * @description N
             */
            discretization_order: number;
            /**
             * Geometry Fingerprint
             * @description Hash of the geometry the bundle was computed for
             */
            geometry_fingerprint: string;
        };
        /**
         * PolygonSchema
         * @description A general polygon defined by >= 3 vertices.
         */
        PolygonSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "polygon";
            /**
             * Vertices
             * @description (r, z) vertices, in boundary order
             */
            vertices: [
                number,
                number
            ][];
        };
        /** PrimaryOutputs */
        PrimaryOutputs: {
            /** Dc Inductance */
            dc_inductance: number;
            /** Lead Inductance */
            lead_inductance: number;
            /** Total Inductance */
            total_inductance: number;
            /**
             * Resonant Frequency
             * @description Null when no tank capacitance is specified
             */
            resonant_frequency?: number | null;
            /** Percent Detuned */
            percent_detuned?: number | null;
            /** Wire Length */
            wire_length: number;
            /** Coil Pitch */
            coil_pitch: number;
            /** Turn Spacing */
            turn_spacing: number;
            /** Dc Resistance */
            dc_resistance: number;
        };
        /**
         * RectangleSchema
         * @description A rectangular region defined by exactly 4 vertices.
         */
        RectangleSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rectangle";
            /**
             * Vertices
             * @description Four (r, z) vertices, in boundary order
             */
            vertices: [
                number,
                number
            ][];
        };
        /**
         * RectangularCrossSectionSchema
         * @description Rectangular (ribbon/strap) conductor.
         */
        RectangularCrossSectionSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "rectangular";
            /**
             * Width
             * @description Radial extent
             */
            width: number;
            /**
             * Height
             * @description Axial extent
             */
            height: number;
        };
        /** SecondaryOutputs */
        SecondaryOutputs: {
            /** Resonant Frequency */
            resonant_frequency: number;
            /** Eigen Frequencies */
            eigen_frequencies: number[];
            /** Dc Inductance */
            dc_inductance: number;
            /** Effective Series Inductance */
            effective_series_inductance: number;
            /** Energy Inductance */
            energy_inductance: number;
            /** Dc Capacitance */
            dc_capacitance: number;
            /** Effective Shunt Capacitance */
            effective_shunt_capacitance: number;
            /** Energy Capacitance */
            energy_capacitance: number;
            /** Topload Effective Capacitance */
            topload_effective_capacitance: number;
            /** Winding Length */
            winding_length: number;
            /** Conductor Length */
            conductor_length: number;
            /** Coil Pitch */
            coil_pitch: number;
            /** Turns Per Length */
            turns_per_length: number;
            /** Turn Spacing */
            turn_spacing: number;
            /** Mean Diameter */
            mean_diameter: number;
            /** Aspect Ratio */
            aspect_ratio: number;
            /** Inclination Degrees */
            inclination_degrees: number;
            /** Reactance At Resonance */
            reactance_at_resonance: number;
            /** Skin Depth */
            skin_depth: number;
            /** Dc Resistance */
            dc_resistance: number;
            /** Ac Resistance */
            ac_resistance: number;
            /** Quality Factor */
            quality_factor: number;
            /** Wire Weight */
            wire_weight: number;
        };
        /**
         * SimulatableTeslaCoilSchema
         * @description A complete coil plus its simulation domain and boundary conditions.
         */
        SimulatableTeslaCoilSchema: {
            secondary: components["schemas"]["LinearSecondaryConductorSchema"];
            primary?: components["schemas"]["LinearPrimarySchema"] | null;
            /** Toploads */
            toploads?: components["schemas"]["ToploadSchema"][];
            /** Grounds */
            grounds?: components["schemas"]["GroundedConductorSchema"][];
            /**
             * R Max
             * @description Radial extent of the domain
             */
            r_max: number;
            /**
             * Z Max
             * @description Vertical extent of the domain
             */
            z_max: number;
            /**
             * Unit Scale
             * @description Meters per geometry unit (e.g. 0.0254 for inches)
             * @default 1
             */
            unit_scale: number;
            /**
             * Discretization Order
             * @description Number of virtual conductor segments
             * @default 30
             */
            discretization_order: number;
            bc_bottom?: components["schemas"]["BoundaryConditionSchema"] | null;
            bc_top?: components["schemas"]["BoundaryConditionSchema"] | null;
            bc_right?: components["schemas"]["BoundaryConditionSchema"] | null;
        };
        /**
         * SpiceRequest
         * @description Export the coupled system as a SPICE subcircuit. Reuses a bundle.
         */
        SpiceRequest: {
            coil: components["schemas"]["SimulatableTeslaCoilSchema"];
            bundle?: components["schemas"]["MatrixBundleSchema"] | null;
            /**
             * Subcircuit Name
             * @description SPICE .subckt name
             * @default teslacoil
             */
            subcircuit_name: string;
        };
        /** SpiceResponse */
        SpiceResponse: {
            /**
             * Netlist
             * @description SPICE subcircuit text
             */
            netlist: string;
            bundle: components["schemas"]["MatrixBundleSchema"];
        };
        /** ToploadSchema */
        ToploadSchema: {
            /** @default aluminum */
            material: components["schemas"]["MaterialSchema"];
            /**
             * Shape
             * @description (r, z) cross-section shape
             */
            shape: components["schemas"]["CircleSchema"] | components["schemas"]["RectangleSchema"] | components["schemas"]["PolygonSchema"];
        };
        /**
         * UniformTurnProfileSchema
         * @description Evenly wound: turns ramp linearly in the curve parameter.
         */
        UniformTurnProfileSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "uniform";
            /**
             * Total Turns
             * @description Total number of turns
             */
            total_turns: number;
            /**
             * T Min
             * @description Curve parameter at the start
             * @default 0
             */
            t_min: number;
            /**
             * T Max
             * @description Curve parameter at the end
             * @default 1
             */
            t_max: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    compute_matrices_simulation_matrices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatricesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatrixBundleSchema"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_simulation_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    impedance_simulation_impedance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpedanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpedanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spice_simulation_spice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpiceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpiceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    field_simulation_field_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
