"""
Cross-language contract for the primary's ring spacing.

The 2-D editor and the 3-D viewer both draw the primary as one ring per
turn. Those rings MUST land exactly where the physics places them -
``PrimarySpec.ring_centers()`` - because that same spacing feeds the
coupling vector, the primary self-inductance, and the electrostatic
grounded-ring solve. If the drawing and the math ever disagree, the
picture is lying about what was solved.

The frontend can't call this Python, so the two sides are pinned to a
shared golden fixture instead:

  * this test regenerates the fixture from ``ring_centers()`` and asserts
    the committed copy still matches (guards the fixture against solver
    drift), and
  * ``frontend/src/editor/primaryRings.test.ts`` loads the SAME file and
    asserts its TypeScript ``primaryRingCenters()`` reproduces it.

If ``ring_centers()`` changes, this test fails until the fixture is
regenerated (``JSTC_REGEN_RING_FIXTURE=1 pytest``); the regenerated
fixture then fails the TS test until the TypeScript is updated to match.
Neither side can drift silently.
"""
import json
import os
from pathlib import Path

import pytest

from app.geometry import CircularCrossSection
from app.models.coil_models import LinearPrimarySpec
from app.models.materials import Material
from app.models.turn_profiles import UniformTurnProfile

# Repo-root-relative path to the fixture the frontend test imports.
# api/tests/models/<this file>  ->  parents[3] == repo root.
FIXTURE_PATH = (
    Path(__file__).resolve().parents[3]
    / "frontend"
    / "src"
    / "editor"
    / "__fixtures__"
    / "primaryRings.json"
)

# Input cases spanning the primary shapes the editor can produce: flat
# spirals (horizontal), helices (vertical), saucers (slanted), reversed
# winding direction, a single turn, many turns, an integer and a fractional
# final turn, and a non-default turn-parameter window. Each is a straight
# centerline wound uniformly - exactly what LinearPrimarySpec +
# UniformTurnProfile represents, and all the UI can build.
CASES = [
    {"name": "javatc-flat-spiral", "start": [3.75, 23.0], "end": [7.969, 23.0], "total_turns": 8.438},
    {"name": "integer-flat-spiral", "start": [3.0, 10.0], "end": [7.0, 10.0], "total_turns": 8.0},
    {"name": "single-turn", "start": [2.0, 5.0], "end": [3.0, 5.0], "total_turns": 1.0},
    {"name": "vertical-helix", "start": [4.0, 20.0], "end": [4.0, 26.0], "total_turns": 6.0},
    {"name": "slanted-saucer", "start": [3.0, 12.0], "end": [9.0, 18.0], "total_turns": 10.0},
    {"name": "reversed-direction", "start": [8.0, 30.0], "end": [3.0, 30.0], "total_turns": 5.0},
    {"name": "many-turns", "start": [2.5, 0.0], "end": [12.5, 0.0], "total_turns": 24.0},
    {"name": "fractional-few", "start": [1.0, 1.0], "end": [4.0, 2.0], "total_turns": 3.75},
    {
        # A non-default turn-parameter window (the winding occupies only part
        # of the curve's parameter range). The editor only ever builds [0, 1]
        # windows, but the TS port mirrors the full algorithm, so pin one
        # general case. t_max=0.8 keeps `total` cleanly fractional (8.75),
        # away from any ceil() knife-edge.
        "name": "partial-turn-window",
        "start": [2.0, 40.0],
        "end": [6.0, 40.0],
        "total_turns": 7.0,
        "t_min": 0.0,
        "t_max": 0.8,
    },
]


def _spec(case: dict) -> LinearPrimarySpec:
    profile = UniformTurnProfile(
        case["total_turns"],
        t_min=case.get("t_min", 0.0),
        t_max=case.get("t_max", 1.0),
    )
    return LinearPrimarySpec(
        material=Material.COPPER,
        turn_fxn=profile,
        cross_section=CircularCrossSection(diameter=0.25),
        start=tuple(case["start"]),
        end=tuple(case["end"]),
    )


def _expected_fixture() -> dict:
    return {
        "_comment": (
            "Golden primary ring centers from PrimarySpec.ring_centers(). "
            "Generated by api/tests/models/test_primary_ring_fixture.py "
            "(JSTC_REGEN_RING_FIXTURE=1). Consumed by that test and by "
            "frontend/src/editor/primaryRings.test.ts to keep the UI ring "
            "spacing identical to the solver's."
        ),
        "cases": [
            {**case, "ring_centers": [[r, z] for r, z in _spec(case).ring_centers()]}
            for case in CASES
        ],
    }


def test_ring_fixture_matches_solver():
    fixture = _expected_fixture()

    if os.environ.get("JSTC_REGEN_RING_FIXTURE"):
        FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE_PATH.write_text(json.dumps(fixture, indent=2) + "\n")

    assert FIXTURE_PATH.exists(), (
        f"Missing fixture {FIXTURE_PATH}. Regenerate with "
        f"JSTC_REGEN_RING_FIXTURE=1 pytest."
    )
    committed = json.loads(FIXTURE_PATH.read_text())

    assert [c["name"] for c in committed["cases"]] == [c["name"] for c in CASES]
    for expected, actual in zip(fixture["cases"], committed["cases"]):
        assert expected["name"] == actual["name"]
        exp_centers = expected["ring_centers"]
        act_centers = actual["ring_centers"]
        assert len(exp_centers) == len(act_centers), expected["name"]
        for (er, ez), (ar, az) in zip(exp_centers, act_centers):
            assert er == pytest.approx(ar, abs=1e-9, rel=1e-9), expected["name"]
            assert ez == pytest.approx(az, abs=1e-9, rel=1e-9), expected["name"]
